name: BSD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  freebsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/freebsd-vm@83b151f58c6047089f4c80eb5ba2039d158ce093 # v1.5.3
        with:
          usesh: true
          sync: rsync
          copyback: false
          prepare: pkg install -y rust
          run: |
            cargo build
            cargo test --tests
  netbsd:
    name: NetBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/netbsd-vm@00081e82b14bc40114eb97f32b4455306828516b # v1.4.6
        with:
          usesh: true
          sync: rsync
          copyback: false
          prepare: |
            pkg_add rust
            # We need to use a disk image that actually supports
            # extended attributes.
            dd if=/dev/zero of=/disk.img bs=1m count=100
            vnconfig vnd0 /disk.img
            newfs -O 2ea /dev/rvnd0a
            mkdir /mnt/loop
            mount /dev/vnd0a /mnt/loop
          run: |
            cargo build
            TMPDIR=/mnt/loop cargo test --tests
  midnight:
    name: MidnightBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/midnightbsd-vm@1629088a95a63a7273cf57603b13e5e247417549 # v1.0.4
        with:
          usesh: true
          sync: rsync
          copyback: false
          prepare: mport --quiet install rust >/dev/null || true
          run: |
            cargo build
            cargo test --tests
