name: BSD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  freebsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/freebsd-vm@b84ab5559b5a1bb4b8ee2737d2506a16e1737636 # v1.4.8
        with:
          usesh: true
          sync: rsync
          copyback: false
          prepare: pkg install -y rust
          run: |
            cargo build
            cargo test --tests
  netbsd:
    name: NetBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/netbsd-vm@0c26a4c4a5e234038862a4a53a00c905b8a107c9 # v1.4.2
        with:
          usesh: true
          sync: rsync
          copyback: false
          prepare: |
            pkg_add rust
            # We need to use a disk image that actually supports
            # extended attributes.
            dd if=/dev/zero of=/disk.img bs=1m count=100
            vnconfig vnd0 /disk.img
            newfs -O 2ea /dev/rvnd0a
            mkdir /mnt/loop
            mount /dev/vnd0a /mnt/loop
          run: |
            cargo build
            TMPDIR=/mnt/loop cargo test --tests
  midnight:
    name: MidnightBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/midnightbsd-vm@b000e438e1a4c7986a8f0b8b7b3805d4a41945db # v1.0.3
        with:
          usesh: true
          sync: rsync
          copyback: false
          prepare: mport --quiet install rust >/dev/null || true
          run: |
            cargo build
            cargo test --tests
