on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: linux

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c
      with:
        toolchain: stable
    - run: cargo build --verbose
    - run: cargo test --verbose
