on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: macos

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo build --verbose
    - run: cargo test --verbose
