on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: unsupported

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-gnu
    - run: cargo build --verbose --target x86_64-pc-windows-gnu
